from beam_integrals import DEFAULT_MAX_MODE, DEFAULT_DECIMAL_PRECISION


MAX_MODE = DEFAULT_MAX_MODE
DECIMAL_PRECISION = DEFAULT_DECIMAL_PRECISION

MAX_ERROR_TOLERANCE_DECIMALS = 16
MAX_ERROR_TOLERANCE = 10 ** -MAX_ERROR_TOLERANCE_DECIMALS
